name: desbrav
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  sizer: ^2.0.15
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  fl_chart: ^0.65.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  provider: ^6.1.1
  supabase_flutter: ^2.8.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

  web: any
  geolocator: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/